apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: social-network-ingress
  labels:
    name: social-network-ingress
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "600"
spec:
  rules:
    - host: social-network.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: nginx-thrift
                port:
                  number: 8080
          - path: /media-frontend
            pathType: Prefix
            backend:
              service:
                name: media-frontend
                port:
                  number: 8081
